#pragma once

#ifndef CPP_SEARCH_SERVER_CONSTANTS_H
#define CPP_SEARCH_SERVER_CONSTANTS_H

const int MAX_RESULT_DOCUMENT_COUNT = 5;
const double EPS = 1e-6;
const int MIN_IN_DAY = 1440;

#endif //CPP_SEARCH_SERVER_CONSTANTS_H
